# Generated by Django 2.0.3 on 2018-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('creation_date', 'name'),
            },
        ),
    ]
